//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meowdoku.Solver {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Meowdoku.Solver.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string LoadScreenText {
            get {
                return ResourceManager.GetString("LoadScreenText", resourceCulture);
            }
        }
        
        internal static string OrText {
            get {
                return ResourceManager.GetString("OrText", resourceCulture);
            }
        }
        
        internal static string ColorManuallyText {
            get {
                return ResourceManager.GetString("ColorManuallyText", resourceCulture);
            }
        }
        
        internal static string GameFieldSizeText {
            get {
                return ResourceManager.GetString("GameFieldSizeText", resourceCulture);
            }
        }
        
        internal static string AvailableColorsText {
            get {
                return ResourceManager.GetString("AvailableColorsText", resourceCulture);
            }
        }
        
        internal static string ClearGameFieldText {
            get {
                return ResourceManager.GetString("ClearGameFieldText", resourceCulture);
            }
        }
        
        internal static string SolveLevelText {
            get {
                return ResourceManager.GetString("SolveLevelText", resourceCulture);
            }
        }
        
        internal static string ErrorSolutionResultText {
            get {
                return ResourceManager.GetString("ErrorSolutionResultText", resourceCulture);
            }
        }
        
        internal static string SuccessSolutionResultText {
            get {
                return ResourceManager.GetString("SuccessSolutionResultText", resourceCulture);
            }
        }
        
        internal static string ErrorGridDetectionText {
            get {
                return ResourceManager.GetString("ErrorGridDetectionText", resourceCulture);
            }
        }
        
        internal static string GridDetectionRowColCountNotEqualText {
            get {
                return ResourceManager.GetString("GridDetectionRowColCountNotEqualText", resourceCulture);
            }
        }
        
        internal static string FileSizeTooSmallText {
            get {
                return ResourceManager.GetString("FileSizeTooSmallText", resourceCulture);
            }
        }
        
        internal static string TooLittleSquaresErrorText {
            get {
                return ResourceManager.GetString("TooLittleSquaresErrorText", resourceCulture);
            }
        }
        
        internal static string GridDetector_ClusterColors_Clusters_count_must_be_positive {
            get {
                return ResourceManager.GetString("GridDetector_ClusterColors_Clusters_count_must_be_positive", resourceCulture);
            }
        }
        
        internal static string ColumnsCountMismatchErrorText {
            get {
                return ResourceManager.GetString("ColumnsCountMismatchErrorText", resourceCulture);
            }
        }
    }
}
