//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meowdoku.Solver.Static {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Meowdoku.Solver.Static.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string page_title {
            get {
                return ResourceManager.GetString("page-title", resourceCulture);
            }
        }
        
        internal static string page_summary_descr {
            get {
                return ResourceManager.GetString("page-summary-descr", resourceCulture);
            }
        }
        
        internal static string descr_summary {
            get {
                return ResourceManager.GetString("descr-summary", resourceCulture);
            }
        }
        
        internal static string original_game_title {
            get {
                return ResourceManager.GetString("original-game-title", resourceCulture);
            }
        }
        
        internal static string local_work_title {
            get {
                return ResourceManager.GetString("local-work-title", resourceCulture);
            }
        }
        
        internal static string local_work_description {
            get {
                return ResourceManager.GetString("local-work-description", resourceCulture);
            }
        }
        
        internal static string auto_recognition_title {
            get {
                return ResourceManager.GetString("auto-recognition-title", resourceCulture);
            }
        }
        
        internal static string auto_recognition_description {
            get {
                return ResourceManager.GetString("auto-recognition-description", resourceCulture);
            }
        }
        
        internal static string open_source_title {
            get {
                return ResourceManager.GetString("open-source-title", resourceCulture);
            }
        }
        
        internal static string open_source_description {
            get {
                return ResourceManager.GetString("open-source-description", resourceCulture);
            }
        }
        
        internal static string feedback_title {
            get {
                return ResourceManager.GetString("feedback-title", resourceCulture);
            }
        }
        
        internal static string feedback_description {
            get {
                return ResourceManager.GetString("feedback-description", resourceCulture);
            }
        }
        
        internal static string sell_text {
            get {
                return ResourceManager.GetString("sell-text", resourceCulture);
            }
        }
        
        internal static string start_button_text {
            get {
                return ResourceManager.GetString("start-button-text", resourceCulture);
            }
        }
    }
}
